language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - yarn run test
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm install -g codecov
  - codecov
branches:
  only:
    - master
env:
  global:
  - secure: Ok+JHub1XDkidt18XgW09qV8Q2sAq9Wz1vmDYX66guJiwnLOGeEEqgmIqPxbVSgK9xIsfrnyf6uxpz1+r20A2EWxzeiAVpEN15SzPs1QGvYVSnDxIiXmOEkJLsW5XOA1NItKVnwI1krbnEBM0jf8oRqIMNQYVhGsucd2rPtx7VbY0HjH/f2cXWBB37/7F1TEkbv/DUu9Rjm9jW9QbhKkWrotBj5KMt5jekHa/rG0AlRH67/ECDV0yjR+HfQWx+L7JR4j6ZHR0SPAMYCfFmynBOzk3y2bkzHxmpRQi1gsoeacbZ1eFkTag9YCXiSXzwZkxGY95d8ooRtOIgdh6Mn/HhGmQqHrB+/KP4AchZIi/Ruf7Bw46u5SrlNqRkCUNGB0OOY82k0CNKl8PuJK5uaqODQkit+dljiImB319F3IVWrVTXD4MbNBQb1leULQ+eGLWjvd4uSlFiDq2O9JYtUYsbaaxJbT+EvDUxBLPkdwvXT8E2UiYxbfSJ+vFtsuzuZnsmwkXB/LucRW+Mq1QAUMU497zWWlRaekAf8KSmr9lr/pFj5+VPDLfhgfXloxCPM19ZBPheRAEpjCWYp8+7PKeRe+Si/kWwkVYbHQVFlQ/M19zXQGPd3xz+VAWNGyYsdia120KwlTzWEda7r5KZ66wYbk6ZbIKYLFDr/COLP/s6w=
  - secure: b5o7X7qxltcNuklVmtjFUgdQPwW2G3tpvg6xZXRrUE0U2GHNsK8e3GXrPYoeMzPebwq+J45970ZxjSwWIh0yzJvLYDD0rQCIehp5DwMIAhWlZS+hz+f3nxpdiqNJpagDlJX/zdzdfVVTKxwRxRYOrkV/fdXVLNIwtwBauUl90fM4PcgFnVefGFYqoSBiAthD99TggpM4yjOM6+egxKLgui7mb2MOKNEmcuzHF6JCCSyYj8ggkBOU1aeEULVoPlD1MIPvC6+9qoKKnwvB/6J+FdvUQkhSYqkvY0ImxIfXzpj2gbCC6838eqlZ1/jSWjMflxpIw93/JYj3n0SmrxRoSvzLvoyRVgTYtFYpMQnnGpXhbxwqJ7MUFA3Hz8KvTQgrMiHNoOEdJJ9djf9AjNRwdZjuPlRxMagopsits0IOXanCBT23ac3JwpyH04D71h7tnRWiWBzaFyJE+hLc1YfvJuKwJ0OEC/meDHrIUgmdx1zWG42y8sFYJ/giZ6j6IUaiRKSumFv0EyI3wZFjoZVILvqHaiYimaQh5SrltqlAZ30gYlf7ZBJiTqZm30l8RvOEhdkTmCbxFwvu2KbOBdgpNzEV/DtyMR2CAG0ho/hzCsxGzDC4+1sbzDuA8fTD+zgIt3JAGxt6A402qZGQByeedgE68lmnT3Oo02yXueR0aas=
